#pragma config(Sensor, S1,     touchSensor,    sensorNone)
#pragma config(Sensor, S2,     gyroSensor,     sensorNone)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorNone)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, openLoop)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,           ,             tmotorEV3_Large, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

TLegoColors currentColor = colorNone;

task checkColor(){
	TLegoColors tempColor = getColorName(colorSensor);
    while(true){
    	if(tempColor != currentColor){
    		currentColor = tempColor;
      }
        wait1Msec(10);
    }
}

task main()
{
  int threshold = 65;

  // create child thread
  startTask(checkColor);

  while(currentColor != colorBlue)
  {
		switch (currentColor)
		{
	  case colorBlue:

	    break;
	  case colorRed:

	    break;
	  default:
	    // sensor sees light:
        if(getColorReflected(colorSensor) > threshold)
        {
          // counter-steer right:
          motor[leftMotor]  = 15;
          motor[rightMotor] = 55;
        }
        // sensor sees dark:
        else
        {
          // counter-steer left:
          motor[leftMotor]  = 55;
          motor[rightMotor] = 15;
        }
	  }
    wait1Msec(10);
	}
}
